[project]
name = "transactions-model"
version = "0.1.0"
dependencies = [
    "beanie",
    "iso4217",
]

[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[tool.black]
line-length = 88
target-version = ["py38"]

[tool.isort]
profile = "black"