services:
    workspace:
        build: .
        tty: true
        stdin_open: true
        volumes:
            - ..:/workspace:cached
            - db-data:/data/db/transactions
        env_file:
            - ../.env
    db:
        image: mongo:latest
        volumes:
            - db-data:/data/db/transactions
        restart: unless-stopped
    mongo-express:
        image: mongo-express
        environment:
            ME_CONFIG_MONGODB_SERVER: db
        depends_on:
            - db
        restart: unless-stopped
volumes:
    db-data: